feat: Add property to register on sip TLS socket disconnects.
With jigasi we are seeing frequent TLS socket disconnects, the stream is closed. Next message to be sent re-establishes it, but keeps provider unregistered on the sip side causing timeouts.

This is a hack detecting these disconnects through the log messages from the sip stack.

2022-10-20 11:34:34.779 FINE: [17210] net.java.sip.communicator.impl.protocol.sip.SipLogger.logDebug: Debug output from the JAIN-SIP stack: sendBytes TLS local inAddr 0:0:0:0:0:0:0:0 remote inAddr X.X.X.X port = 5061 length = 925 isClient true
2022-10-20 11:34:34.846 FINE: [18404] net.java.sip.communicator.impl.protocol.sip.SipLogger.logDebug: Debug output from the JAIN-SIP stack: Received CRLF
2022-10-20 11:34:34.846 FINE: [18404] net.java.sip.communicator.impl.protocol.sip.SipLogger.logDebug: Debug output from the JAIN-SIP stack: KeepAlive Double CRLF received, sending single CRLF as defined per RFC 5626 Section 4.4.1
2022-10-20 11:34:34.846 FINE: [18404] net.java.sip.communicator.impl.protocol.sip.SipLogger.logDebug: Debug output from the JAIN-SIP stack: ~~~ setting isPreviousLineCRLF=false
2022-10-20 11:34:34.846 FINE: [18404] net.java.sip.communicator.impl.protocol.sip.SipLogger.logDebug: Debug output from the JAIN-SIP stack: sendMessage isClient  = false
2022-10-20 11:34:34.846 FINE: [18404] net.java.sip.communicator.impl.protocol.sip.SipLogger.logDebug: Debug output from the JAIN-SIP stack: sendBytes TLS local inAddr 0:0:0:0:0:0:0:0 remote inAddr X.X.X.X port = 5061 length = 2 isClient false
2022-10-20 11:34:34.846 WARNING: [18404] net.java.sip.communicator.impl.protocol.sip.SipLogger.logException: Exception in the JAIN-SIP stack: Socket is closed
2022-10-20 11:34:34.846 INFO: [18404] net.java.sip.communicator.impl.protocol.sip.SipLogger.logException: JAIN-SIP exception stack trace is
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getOutputStream(SSLSocketImpl.java:1234)
	at gov.nist.javax.sip.stack.IOHandler.sendBytes(IOHandler.java:460)
	at gov.nist.javax.sip.stack.TLSMessageChannel.sendMessage(TLSMessageChannel.java:238)
	at gov.nist.javax.sip.stack.ConnectionOrientedMessageChannel.sendSingleCLRF(ConnectionOrientedMessageChannel.java:715)
	at gov.nist.javax.sip.parser.PipelinedMsgParser.run(PipelinedMsgParser.java:368)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-10-20 11:34:34.846 FINE: [18403] net.java.sip.communicator.impl.protocol.sip.SipLogger.logDebug: Debug output from the JAIN-SIP stack: Closing socket tls:X.X.X.X:5061
2022-10-20 11:34:34.846 FINE: [18404] net.java.sip.communicator.impl.protocol.sip.SipLogger.logDebug: Debug output from the JAIN-SIP stack: removed Socket and Semaphore for key X.X.X.X:5061
2022-10-20 11:34:34.846 FINE: [18403] net.java.sip.communicator.impl.protocol.sip.SipLogger.logDebug: Debug output from the JAIN-SIP stack: Closing my parser gov.nist.javax.sip.parser.PipelinedMsgParser@3f5c01c
2022-10-20 11:34:34.846 FINE: [18404] net.java.sip.communicator.impl.protocol.sip.SipLogger.logDebug: Debug output from the JAIN-SIP stack: Closing socket
2022-10-20 11:34:34.846 FINE: [18403] net.java.sip.communicator.impl.protocol.sip.SipLogger.logDebug: Debug output from the JAIN-SIP stack: Closing pipelinedmsgparser gov.nist.javax.sip.parser.PipelinedMsgParser@3f5c01c threadname PipelineThread-12
2022-10-20 11:34:34.846 FINE: [18403] net.java.sip.communicator.impl.protocol.sip.SipLogger.logDebug: Debug output from the JAIN-SIP stack: Closing TLS socket X.X.X.X:5061
2022-10-20 11:34:34.846 FINE: [18403] net.java.sip.communicator.impl.protocol.sip.SipLogger.logDebug: Debug output from the JAIN-SIP stack: removed Socket and Semaphore for key X.X.X.X:5061
2022-10-20 11:34:34.846 FINE: [18403] net.java.sip.communicator.impl.protocol.sip.SipLogger.logDebug: Debug output from the JAIN-SIP stack: Closing message Channel (key = tls:X.X.X.X:5061)gov.nist.javax.sip.stack.TLSMessageChannel@2de45980
2022-10-20 11:34:34.846 WARNING: [18404] net.java.sip.communicator.impl.protocol.sip.SipLogger.logWarning: Warning from the JAIN-SIP stackFailed to connect mysipserver.com/X.X.X.X:5061 but trying the advertised port=5061 if it's different than the port we just failed on
2022-10-20 11:34:34.846 FINE: [18403] net.java.sip.communicator.impl.protocol.sip.SipLogger.logDebug: Debug output from the JAIN-SIP stack: Thread[TCPMessageChannelThread,5,main] removing tls:X.X.X.X:5061 for processor /0:0:0:0:0:0:0:0:5061/tls
2022-10-20 11:34:34.847 SEVERE: [18404] net.java.sip.communicator.impl.protocol.sip.SipLogger.logError: Error from the JAIN-SIP stack: Error is
java.io.IOException: Could not connect to mysipserver.com/X.X.X.X:5061
	at gov.nist.javax.sip.stack.IOHandler.sendBytes(IOHandler.java:490)
	at gov.nist.javax.sip.stack.TLSMessageChannel.sendMessage(TLSMessageChannel.java:238)
	at gov.nist.javax.sip.stack.ConnectionOrientedMessageChannel.sendSingleCLRF(ConnectionOrientedMessageChannel.java:715)
	at gov.nist.javax.sip.parser.PipelinedMsgParser.run(PipelinedMsgParser.java:368)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-10-20 11:34:34.847 FINE: [18403] net.java.sip.communicator.impl.protocol.sip.SipLogger.logDebug: Debug output from the JAIN-SIP stack: Thread[TCPMessageChannelThread,5,main] Removing incoming channel tls:X.X.X.X:5061 for processor /0:0:0:0:0:0:0:0:5061/tls
2022-10-20 11:34:34.847 FINE: [18403] net.java.sip.communicator.impl.protocol.sip.SipLogger.logDebug: Debug output from the JAIN-SIP stack: Closing pipelinedmsgparser gov.nist.javax.sip.parser.PipelinedMsgParser@3f5c01c threadname PipelineThread-12
2022-10-20 11:34:34.847 WARNING: [18404] net.java.sip.communicator.impl.protocol.sip.SipLogger.logWarning: Warning from the JAIN-SIP stackCouldn't connect to peerAddress = mysipserver.com/X.X.X.X peerPort = 5061 key = tls:X.X.X.X:5061 retrying on peerPortAdvertisedInHeaders 5061
2022-10-20 11:34:34.847 FINE: [18404] net.java.sip.communicator.impl.protocol.sip.SipLogger.logDebug: Debug output from the JAIN-SIP stack: sendBytes TLS local inAddr 0:0:0:0:0:0:0:0 remote inAddr X.X.X.X port = 5061 length = 2 isClient false
2022-10-20 11:34:34.847 FINE: [18404] net.java.sip.communicator.impl.protocol.sip.SipLogger.logDebug: Debug output from the JAIN-SIP stack: new Semaphore added for key X.X.X.X:5061
2022-10-20 11:34:34.847 FINE: [18404] net.java.sip.communicator.impl.protocol.sip.SipLogger.logDebug: Debug output from the JAIN-SIP stack: removed Socket and Semaphore for key X.X.X.X:5061
2022-10-20 11:34:34.847 SEVERE: [18404] net.java.sip.communicator.impl.protocol.sip.SipLogger.logError: Error from the JAIN-SIP stack: A problem occured while trying to send a single CLRF in response to a double CLRF
java.io.IOException: Could not connect to /X.X.X.X:5061
	at gov.nist.javax.sip.stack.IOHandler.sendBytes(IOHandler.java:490)
	at gov.nist.javax.sip.stack.TLSMessageChannel.sendMessage(TLSMessageChannel.java:250)
	at gov.nist.javax.sip.stack.ConnectionOrientedMessageChannel.sendSingleCLRF(ConnectionOrientedMessageChannel.java:715)
	at gov.nist.javax.sip.parser.PipelinedMsgParser.run(PipelinedMsgParser.java:368)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-10-20 11:34:34.847 FINE: [18404] net.java.sip.communicator.impl.protocol.sip.SipLogger.logDebug: Debug output from the JAIN-SIP stack: thread ending for threadname PipelineThread-12
2022-10-20 11:34:34.847 FINEST: [18404] net.java.sip.communicator.impl.protocol.sip.SipLogger.logStackTrace: JAIN-SIP stack trace
java.lang.Throwable
	at net.java.sip.communicator.impl.protocol.sip.SipLogger.logStackTrace(SipLogger.java:73)
	at gov.nist.core.CommonLogger.logStackTrace(CommonLogger.java:116)
	at gov.nist.javax.sip.parser.PipelinedMsgParser.run(PipelinedMsgParser.java:405)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-10-20 11:34:34.847 FINE: [18404] net.java.sip.communicator.impl.protocol.sip.SipLogger.logDebug: Debug output from the JAIN-SIP stack: cleaned the messagesOrderingMap gov.nist.javax.sip.parser.PipelinedMsgParser@3f5c01c threadname PipelineThread-12
2022-10-20 11:34:39.648 FINE: [17217] net.java.sip.communicator.impl.protocol.sip.SipLogger.logDebug: Debug output from the JAIN-SIP stack: creating new TLSMessageChannel (outgoing)