AppIndicator: Update OSGi after Re-architecting.
AppIndicator uses org/jitsi/utils/logging/Logger. Therefore, when enabled via Menu » Tools » Options » General » Tray implementation, a NoClassDefFoundError was thrown at the start of Jitsi Desktop.