Update OSGi after Re-architecting. (#629)
* AppIndicator: Update OSGi after Re-architecting.

AppIndicator uses org/jitsi/utils/logging/Logger. Therefore, when enabled via Menu » Tools » Options » General » Tray implementation, a NoClassDefFoundError was thrown at the start of Jitsi Desktop.

* AppIndicator: Update OSGi after Re-architecting.

LoginByClientCertificateStrategy uses org/jitsi/utils/logging/Logger.

* DemuxContactSource: Update OSGi after Re-architecting.

DemuxContactSource uses org/jitsi/utils/StringUtils and org/jitsi/utils/logging/Logger. As a side effect, the line-ending of the whole file got normalized.

* JdbcConfigService: Update OSGi after Re-architecting.

JdbcConfigService uses org/jitsi/utils/StringUtils.

* DNS: Update OSGi after Re-architecting.

ConfigurableDnssecResolver uses org/jitsi/utils/StringUtils. 
DnsUtilActivator uses org/jitsi/utils/StringUtils.

* CertConfigEntryDialog: Update OSGi after Re-architecting.

CertConfigEntryDialog uses org/jitsi/utils/StringUtils.

* PhoneNumberContactQuery: Update OSGi after Re-architecting.

PhoneNumberContactQuery uses org/jitsi/utils/StringUtils.

* BusyLampField: Update OSGi after Re-architecting.

BLFContactSourceService uses org/jitsi/utils/StringUtils.

* AccountInfo: Update OSGi after Re-architecting.

AccountDetailsPanel uses org/jitsi/utils/StringUtils.

* HttpUtil: Update OSGi after Re-architecting.

HttpUtils uses org/jitsi/utils/StringUtils.